### ISSUE TITLE
Headline phone image is distorted and pixelated (fix suggestion)

### ISSUE THREAD

**Issue by florian-s-code** [copperhead/website-bugtracker#7]
Because of css sizing, the image is distorted and pixelated.
![screenshot-2017-11-1 copperheados - secure mobile devices](https://user-images.githubusercontent.com/2287301/32300956-1ca52410-bf5c-11e7-8908-96da5d7587c4.png)

Suggested minimal changes :
- change `width` to `max-width` to avoid displaying it too large and pixelation
- add `height` declaration to keep ratio

Current android.css (from line 11) :
```css
.headline-phone .headline-phone-image img {
	width: 94%;
	margin: 0 auto 40px;
}
```
New android.css :
```css
.headline-phone .headline-phone-image img {
	max-width: 94%;
	height: auto;
	margin: 0 auto 40px;
}
```
